### ISSUE TITLE
Still crashing

### ISSUE THREAD

**Issue by kzali** [srtucker22/quasar#2]
This is the log sorry 
Your app is crashing. Here's the latest log.

/home/kam/.meteor/packages/meteor-tool/.1.1.4.xvre8c++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Cannot read property 'appId' of undefined
    at server/lib/config.jsx:8:34
    at /home/kam/quasar/.meteor/local/build/programs/server/app/server/lib/config.jsx.js:18:3
    at /home/kam/quasar/.meteor/local/build/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/home/kam/.meteor/packages/meteor-tool/.1.1.4.xvre8c++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /home/kam/quasar/.meteor/local/build/programs/server/boot.js:117:5
Exited with code: 8
Your application is crashing. Waiting for file change.

                             Could be that I am doing something wrong with settings .json

                            also saw this in  scss.json

"useIndex" : true,
  "includePaths": [
    ".meteor/local/build/programs/server/assets/packages/wolves_bourbon"
  ],
  "indexFilePath" : "client/scss/main.scss"

**Comment by srtucker22** [comment]
no worries. thanks again for calling it out.

<code>"includePaths": [
".meteor/local/build/programs/server/assets/packages/wolves_bourbon"
],</code> needed to go for sure

Your app was actually crashing due to the settings.json config. config.jsx was looking for facebook credentials, which the app actually doesn't use right now, so I've commented out that section of the config.jsx file. You will still need Google credentials in your settings.json however because the app lets users log in with Google. So your settings.json file should look at least something like:

        {
          "google" : {
            "clientId" : "YOUR_CLIENT_ID",
            "clientSecret" : "YOUR_CLIENT_SECRET"
          },
        }

to run the app with the settings: <code>meteor --settings yourpathtosettings/settings.json</code>

You can also always rip out the Google stuff if you're not interested in using it. Pretty sure all you would need to do is comment out the requirements in <a href="https://github.com/srtucker22/quasar/blob/master/server/lib/config.jsx">config.jsx</a> and change the <a href="https://github.com/srtucker22/quasar/blob/master/client/components/modules/header.component.jsx">header.component.jsx</a> component to not loginWithGoogle.

Let me know if it works out!

**Comment by srtucker22** [comment]
whoops didn't mean to close the issue until you resolved it. feel free to reopen if it's not working still

**Comment by srtucker22** [comment]
didn't mean to close the issue till it was resolved.

if everything's good on your end, we can close it :)

**Comment by kzali** [comment]
Thanks was getting a parse error on settings.json however when I manually
typed it and removed the comma after the second last curly it worked great.

{
      "google" : {
        "clientId" : "YOUR_CLIENT_ID",
        "clientSecret" : "YOUR_CLIENT_SECRET"
      }
    }


I works great will play around and get back to you.  will star the
project tonight.


regards
