### ISSUE TITLE
Can't get the demo to work.

### ISSUE THREAD

**Issue by jennyyuejin** [srtucker22/quasar#5]
Hello, thanks for an interesting project! However, I couldn't get it to work on the demo site -- clicking the "video chat" button doesn't work. I'm on El Capitan and the latest version of Chrome.
Is there any extra set up that I needed to do? Thanks!

**Comment by sonicviz** [comment]
Try this one https://quasar-collab.meteor.com/ 
Tested on win/OSX works fine (though meteor demo hosting seems to cut it out after ~15 mins)

**Comment by jennyyuejin** [comment]
Thanks for the lightning fast reply! and... *IT'S ALIVE*!!!
I'm super impressed by how it works with the hardware (i.e. video camera) of the machine. Does this also work on mobile devices?

**Comment by sonicviz** [comment]
You're welcome! Mobile is in the works afaik

**Comment by srtucker22** [comment]
Thanks @sonicviz  for fielding this. 

<a href="https://quasar.meteor.com">quasar.meteor.com</a> demo should be working -- it's still on an older version though and I've noticed that it can be very slow to start a room. I should probably indicate that a room is loading when you click the button. I'll be sure to update the demo soon.

Mobile is in the works. I haven't had a ton of time to dedicate to the project in between work and vacation, but I'm currently in the middle of building mobile support. The challenge has definitely been getting it working on iOS, so maybe I'll release android support first.

Thanks for checking it out and feel free to shoot any more issues or questions!

**Comment by jennyyuejin** [comment]
Thanks a lot, guys. Are you guys planning to get mobile working using sth like react native or meteorjs?
Maybe I could help on the react native front when i get time in a month or two.

**Comment by srtucker22** [comment]
Any contributions more than welcome!

I originally wanted to go the React Native route because there aren't many projects out there, but after some investigation it just looked too underdeveloped especially with WebRTC support to put in the effort. From the feedback I've been getting so far, it seems people are eager to get WebRTC up and running, and I'd rather make that process as smooth as possible before building a bunch of React Native WebRTC stuff -- although that could be a useful project in it of itself. 

So I've started using the solid Cordova support built into Meteor to build out the mobile version. I've been playing with some Cordova WebRTC projects dealing with iOS support like <a href="https://github.com/alongubkin/phonertc">phoneRTC</a> and <a href="https://github.com/eface2face/cordova-plugin-iosrtc/">cordova-plugin-iosrtc</a> and will probably implement the latter although I see a bunch of issues about Meteor support. That said, it looks pretty built out with a decent community, so happy to dive into it a bit and try and make it Meteor friendly.

Anyway, that's the plan right now. I'll look to push out the android branch as it stands next week or so when I'm in front of the computer with the changes I didn't push :scream: , and my goal is to get android up and running properly and pretty before end of Jan.

**Comment by jennyyuejin** [comment]
That's awesome!

**Comment by sonicviz** [comment]
Yes, that whole mobile React thing is a bit funky atm. 

Look forward to the next iteration.
